import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:echo_locate/shared/models/measurement_point.dart';

part 'database.g.dart'; // Generated by build_runner

/// Drift database for EchoLocate measurements and floor plans
@DriftDatabase(tables: [Measurements, FloorPlans, FloorPlanPoints])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 2; // Updated for floor plans

  static QueryExecutor _openConnection() {
    return NativeDatabase.createInBackground(_getDatabaseFile());
  }

  static File _getDatabaseFile() {
    final dir = Directory.systemTemp; // Temporary fix - should use proper path
    return File('${dir.path}/echo_locate.db');
  }

  /// Insert a new measurement
  Future<int> insertMeasurement(MeasurementPoint point) {
    final companion = MeasurementsCompanion.insert(
      x: point.x,
      y: point.y,
      distance: point.distance,
      angle: point.angle,
      signalStrength: point.signalStrength,
      timestamp: point.timestamp.millisecondsSinceEpoch,
    );
    return into(measurements).insert(companion);
  }

  /// Get all measurements ordered by timestamp (newest first)
  Future<List<MeasurementPoint>> getAllMeasurements() async {
    final query = select(measurements)
      ..orderBy([(t) => OrderingTerm.desc(t.timestamp)]);

    final rows = await query.get();
    return rows.map(_measurementFromRow).toList();
  }

  /// Get measurements within a date range
  Future<List<MeasurementPoint>> getMeasurementsByDateRange(
    DateTime start,
    DateTime end,
  ) async {
    final query = select(measurements)
      ..where(
        (t) => t.timestamp.isBetweenValues(
          start.millisecondsSinceEpoch,
          end.millisecondsSinceEpoch,
        ),
      )
      ..orderBy([(t) => OrderingTerm.desc(t.timestamp)]);

    final rows = await query.get();
    return rows.map(_measurementFromRow).toList();
  }

  /// Delete a measurement by ID
  Future<int> deleteMeasurement(int id) {
    return (delete(measurements)..where((t) => t.id.equals(id))).go();
  }

  /// Delete all measurements
  Future<int> deleteAllMeasurements() {
    return delete(measurements).go();
  }

  /// Get measurement count
  Future<int> getMeasurementCount() {
    final count = measurements.id.count();
    final query = selectOnly(measurements)..addColumns([count]);
    return query.map((row) => row.read(count)!).getSingle();
  }

  /// Convert database row to MeasurementPoint
  MeasurementPoint _measurementFromRow(Measurement row) {
    return MeasurementPoint(
      x: row.x,
      y: row.y,
      distance: row.distance,
      angle: row.angle,
      signalStrength: row.signalStrength,
      timestamp: DateTime.fromMillisecondsSinceEpoch(row.timestamp),
    );
  }
}

/// Drift table definition for measurements
class Measurements extends Table {
  IntColumn get id => integer().autoIncrement()();
  RealColumn get x => real()();
  RealColumn get y => real()();
  RealColumn get distance => real()();
  RealColumn get angle => real()();
  RealColumn get signalStrength => real()();
  IntColumn get timestamp => integer()();
}

/// Drift table definition for floor plans
class FloorPlans extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get description => text().nullable()();
  IntColumn get createdAt => integer()();
  IntColumn get updatedAt => integer()();
  IntColumn get totalPoints => integer()();
  RealColumn get areaEstimate => real()();
  IntColumn get measurementDate => integer()();
  IntColumn get scanDuration => integer().nullable()();
  TextColumn get deviceInfo => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Drift table definition for floor plan points
class FloorPlanPoints extends Table {
  TextColumn get id => text()();
  TextColumn get floorPlanId => text().references(FloorPlans, #id)();
  RealColumn get x => real()();
  RealColumn get y => real()();
  RealColumn get distance => real().nullable()();
  RealColumn get angle => real().nullable()();
  RealColumn get signalStrength => real().nullable()();
  IntColumn get measuredAt => integer()();
  TextColumn get pointType => text()();

  @override
  Set<Column> get primaryKey => {id};
}
